#!/usr/bin/env python3

import argparse
import os
import secrets
import string

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('-s', '--size', help='Length', default=16, type=int)
    return parser.parse_args()

DB_FILE = os.path.expanduser('~') + '/.passman'

def main():
    args = parse_args()
    char_set = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(secrets.choice(char_set) for i in range(args.size))
    print(password)

if __name__ == '__main__':
    main()

